### ISSUE TITLE
Príprava dummy outputu z MCU

### ISSUE THREAD

**Issue by DominikDorcak** [jerearth/ecg#3]
Pripraviť program pre posielanie outputu z MCU pre účely testovania. 

- dohodnúť formát posielaných dát : dátová zložka + timestamp
- pre účely testovania postačí posielať náhodné  údaje z rozsahu s timestampom
- implementácia programu pre MCU

**Comment by jerearth** [comment]
Output by mohol byt prostrednictvom stringu, pretoze bude citatelny aj cez hyperterminal.
Format moze byt klasicky CSV stream:
 
timestamp[Uint64],frameType[uint8],Out[V],....

dalsie hodnoty mozno tiez budu, prve dve time a typ riadku

Javascript - pozriet okrem Highcharts aj komplexnu platformu D3 https://d3js.org/
Highcharts - pozrit exmple pre "realtime huge data " - malo by tom byt cez pouzitie  WebGL

MCU:
data sa mozu posielat v zakladnom cykle while v sekvencii adcread -> transferdata
treba mysliet nato z komunikacia bude obojsmerna, takze MCU bude prijimat aj prikzy, neskor dohodneme format, RX cize nacitanie prikazy budme musiet risit cez RX UART ISR, prerusenie pri prijatych dat, kedze out transfer bude synchronny, toto bude musiet ist cez ISR aby sa to nesekalo.
Prikazov bude niekolko pre konfiguraciu , napr veľkost bufrov alebo intervalu dat (time window).
